### ISSUE TITLE
Fix documentation about the use of the mutex.

### ISSUE THREAD

**Issue by ryzhyk** [droundy/internment#10]
I am looking for a Rust interner that is multithreaded and reference counts interned objects, and this looks great. Thanks, @droundy!

The readme says that the global lock is taken "on the interning of new data as well as changing of reference counts". Looking at the code, it's not quite that bad.  I think, in the second case the lock is only taken when the refcount drops to zero. Is this correct?

Also, just curious if you know of other crates (other than hashconsing) that have the same functionality. Most of the ones I was able to find are arena-based, which does not work in my use case.

Thank you!

**Comment by droundy** [comment]
You're welcome!

Yes, you are correct that we don't acquire the global mutex except on creation and freeing of `ArcIntern`. I should fix the documentation (or you could submit a pull request). Right now everything's crazy busy with teaching remotely, so it'll probably be a while.

When I created this crate I looked into various interning options and didn't see anything that satisfied me in terms of simplicity, but that situation could have changed.
