### ISSUE TITLE
Some initial thoughts

### ISSUE THREAD

**Issue by Eh2406** [droundy/internment#2]
I really like this Idea, I look forward to trying it out. I had some thoughts looking over your crate.
- Could you add a licence file? technically most licenses require the file not just an entry in the Cargo.toml.
- Would you consider using MIT/Apache-2.0 licence as it is the most common in the rust community?
- Could  you add links from the readme to the crates.io page and the documentation?
- Could you fill out the rest of Cargo.toml, specifically the part that shows your readme on Crates.io? There is a good gide at: https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata

**Comment by droundy** [comment]
Thanks for the suggestions!
