### ISSUE TITLE
Maintain CHANGELOG

### ISSUE THREAD

**Issue by dvtomas** [droundy/internment#33]
Would it be possible to add and maintain a CHANGELOG.md? It is difficult to know what happened in a new version without one, especially given that the commit messages don't clearly show where the version bumps happened.

Btw, very useful crate, thank you.

**Comment by droundy** [comment]
Do you have an example of a changelog format that you like, with a format I could follow?

**Comment by droundy** [comment]
Note, I'll be closing this shortly, but would still appreciate suggestions regarding the format of the changelog.

**Comment by dvtomas** [comment]
Not really, I maintain my own changelog by hand, introducing each version with a level-two header (`##`). I didn't really investigate, though.
