### ISSUE TITLE
0.5.6 breaks semantic versioning.

### ISSUE THREAD

**Issue by ryzhyk** [droundy/internment#34]
I realize it is too late, but just pointing out in case somebody else runs into this that 0.5.6 requires a newer Rust compiler version than 0.5.5 and thus violates semantic versioning. I think it should have bumped the minor version number (e.g., 0.6.0).

**Comment by droundy** [comment]
There is debate whether changing the MSRV is a semantic versioning break.

https://users.rust-lang.org/t/rust-version-requirement-change-as-semver-breaking-or-not/20980

**Comment by ryzhyk** [comment]
Interesting. My two cents are that the whole point of semantic versioning is that library changes shouldn't break anything for people using the library.  In this case, it certainly broke stuff for our customers :)

Thanks again for this great library!

**Comment by droundy** [comment]
I'm sorry to hear that. The concern I see with MRSV is that if any dependency had a less strict MRSV then one runs into trouble. And if we (create authors) don't know what version the end users are actually using, it's possible to create much churn and difficulty (and keeping bug fixes away from users!) by adding extra major version bumps for every MSRV change.

It would be nice if we had a tool like crater that would allow us to determine whether a chance actually affected end users.  Tracking MSRV is unfortunately hard.

**Comment by droundy** [comment]
I believe that although I didn't fix the issue with the older version, with the latest release I added `rust-version` which should prevent this kind of trouble in the future.
