### ISSUE TITLE
Make `Intern` smaller by using 32-bit arena id?

### ISSUE THREAD

**Issue by danleh** [droundy/internment#35]
Hi! First of all, great work, thanks a lot for your crate! :-)

I wanted to ask if you have plans for a 32-bit size `Intern`, by using `u32` instead of a reference to identify values. I thought of something like `Spur` from the `lasso` crate (although that only does string interning): https://calypso-lang.github.io/rustdoc/lasso/struct.Spur.html

To evaluate the design space a bit more, here a couple of pros and cons for this approach vs. the current implementation with usize references:
- Would only allow for 2^32 unique values (but if one has more than those, the question is why use an interner in the first place.)
- Would only work for `Intern`, not `ArcIntern` (but the code base is anyway already split between the two).
- Would lose niche-optimization (but one could use `NonZeroU32` to get that back).
- Needs a global data structure to map from those u32 Ids back to the interned values (e.g., a `Vec<&T>`) and requires a `HashMap<T, u32>` instead of just a `HashSet` in the `Arena`. Both cost memory, but presumably there exists at least one reference (`Intern`) to each unique value, which means the cost savings of making `Intern` smaller should already roughly offset that (and it only gets better the more `Intern`ed values are referenced.

What do you think? Did you already consider such an implementation in the past? What were the considerations for choosing the current `Intern` implementation?

**Comment by droundy** [comment]
An interesting idea. I've been planning one of these days to put all the types under feature gates, and a 32 bit intern would be a welcome addition there, assuming it's bug-free.  I would worry a bit about implementing the Deref safely, although it should be possible.  The challenge is that you'd need to be able to deref one intern while allocating another in a different thread.

**Comment by danleh** [comment]
I agree, correct parallelism is certainly more of a challenge without the compiler helping with `Send` and `Sync`.
I implemented a little prototype myself, where the `HashMap` (mapping unique values to their `u32` id) and the `Vec` (mapping from id back to values) are both protected by an upgradeable `RwLock` (provided by the `parking_lot` crate.) There, deref'ing (i.e. mapping from id to value) requires only a read lock (where multiple threads could still access), and only interning a new value requires a write lock. The one global lock is certainly not ideal (especially if a lot of values are created). Maybe there is some concurrent bidirectional map datastructure, but for my use case this was good enough:

A rough code sketch (mostly untested, needs better error checking etc.):
```Rust
#[derive(Copy, Clone, Eq, PartialEq, Hash, ...)]
struct Intern<T>(u32);

#[derive(Default)]
struct Arena<T> {
  id_to_val: Vec<&'static T>,
  val_to_id: HashMap<&'static T, u32>
}
lazy_static! {
  static ref ARENA: RwLock<Arena> = RwLock::new(Arena::default());
}

impl<T> Intern<T> {
  pub fn new(value: T) -> Self {
    let arena = ARENA.upgradable_read();
    if let Some(id_value_exists) = arena.get(&value) {
      return Intern(id_value_exists)
    } else {
      let mut arena = RwLockUpgradableReadGuard::upgrade(arena);
      let value_ref = Box::leak(Box::new(value));
      let new_id = arena.id_to_val.len();
      arena.id_to_val.push(value_ref);
      arena.val_to_id.insert(value_ref, new_id); 
      return Intern(new_id)
    }
  }
}
impl<T> Deref for Intern<T> {
  type Target: T
  fn deref(self) -> &T {
    ARENA.read().id_to_val[self.0]
  }
}
```

**Comment by droundy** [comment]
Your sketch looks reasonable to me.  If love to see a patch putting this into a new module under a feature flag. I'd be tempted to call it Intern32, but whatever you like would be great. These  would fit great into a tinyset::Set64 with a Fits64 trait implementation.

**Comment by danleh** [comment]
OK, I am not sure I get to writing a patch in the next weeks, but in case I do, I'll leave a pull request!

I haven't quite understood the tinyset comment: do you mean providing a `Fits64` impl for `Intern32`, such that those ids can be stored in tinyset? Or did you mean replacing the `val_to_id` HashMap by a tinyset (although I wouldn't see a big need for that from a performance standpoint). In any case, I would probably submit something without tinyset for now, as I am not familiar with that crate so much.

**Comment by danleh** [comment]
After a bit of testing with a prototype, I just realized that the proposed `Intern32` is very slow if it is frequently deref'd, because it needs to read-lock the `Vec` each time. Your current `Intern` is much faster, because deref'ing doesn't need to lock and can just follow the pointer, without going through an intermediate lookup.

Unfortunately, this runtime overhead more than nullifies the memory savings of the u32 ids. In conclusion, at least for use cases where derefs occur frequently (which should be most use cases), this proposal is not an improvement. In case someone feels the need for a space-saving version of `Intern`, feel free to implement this, but if you are frequently deref'ing the ids, this is not going to be fast.

**Comment by droundy** [comment]
Thanks for trying the idea out.  I imagine that the trade-off would depend on workload. If you were spending a vast amount of time hashing and comparing interned objects for equality, the cost of deref might not matter much. But maybe such a workload doesn't exist.
