### ISSUE TITLE
Make `parking_lot` optional

### ISSUE THREAD

**Issue by zesterer** [droundy/internment#38]
As of Rust [`1.62`](https://blog.rust-lang.org/2022/06/30/Rust-1.62.0.html#thinner-faster-mutexes-on-linux), sync primitives are significantly faster on Linux. I think this calls for `parking_lot` to be made optional.

**Comment by droundy** [comment]
The major issue is having a const constructor for mutex, which I think should be no problem, but I'd also like to avoid needlessly bumping the MSRV.  Maybe under a different feature flag, if you want to create a pull request?
