### ISSUE TITLE
Add shrink_to_fit to ArcIntern

### ISSUE THREAD

**Issue by ofek-sha** [droundy/internment#44]
As the title says, otherwise the memory might keep growing forever.

The following code can be used:
```
/// Shrinks underlying container's memory to only fit the currently contained items
pub fn shrink_to_fit() {
    Self::get_container().shrink_to_fit();
}
```

Would love to open the PR myself. Thank you!

**Comment by droundy** [comment]
I doubt there is any urgency for this (if so, it's a bit late), but let me know if you'd like me to push a release for this.  Otherwise I'll just wait until more improvements have accumulated.
