### ISSUE TITLE
Is there a way to find out if a value is already interned?

### ISSUE THREAD

**Issue by lfnoise** [droundy/internment#45]
I don't want to intern strings that are typos of things that are. 
Is there a way to check if a value is already interned?

**Comment by droundy** [comment]
No, we don't have a way to do that. It wouldn't be hard to implement if you
wanted to submit a pull request.

David Roundy

**Comment by DanielJoyce** [comment]
Need this for my use case. Will see if I can get PR up.

**Comment by droundy** [comment]
I believe this is completed now.  The API is a little different from what you had, but should work. :crossed_fingers:
