### ISSUE TITLE
`ArcIntern<T>` deadlocks on drop with recursive enum.

### ISSUE THREAD

**Issue by MichaelRawson** [droundy/internment#7]
Hi folks,

Firstly, thanks for the great library: it is very helpful for me in the automatic-theorem-prover world.

Consider the following test case:

```rust
#[test]
fn test_arcintern_nested_drop() {
    #[derive(PartialEq, Eq, Hash)]
    enum Nat {
        Zero,
        Successor(ArcIntern<Nat>)
    }
    let zero = ArcIntern::new(Nat::Zero);
    let one = ArcIntern::new(Nat::Successor(zero));
}
```

At the end of the function, `one` is dropped. The `Drop` implementation for `ArcIntern` takes a lock, then drops the boxed data, then undoes the lock. Unfortunately, the boxed data contains an interned `zero`, which, when dropped, attempts to gain the lock that isn't undone yet.

This code therefore deadlocks on `internment` 0.3.6. PR incoming for this issue. If you would consider testing and merging it to form a new patch release, I would be very grateful.

**Comment by droundy** [comment]
I'm glad to hear you're enjoying this! I'll hopefully soon be able to review your pull request and put out a new release.

**Comment by droundy** [comment]
I just published a fixed version.  Thank you so much!
